export const COLORS = {
    PRIMARY: "#24A19C",
    SECONDARY: "#FFFFFF",
    PRIMARY_TEXT_COLOR: "#1B1C1F",
    SECONDARY_TEXT_COLOR: "#767E8C",
    LIGHT_GRAY_COLOR: "#F3F5F9",
    GHOST_COLOR: "#A9B0C5",
};
